branch-defaults:
  default:
    environment: app-intel
  master:
    environment: null
    group_suffix: null
global:
  application_name: app-intel-pipemanage
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
